// CarlaNet.Map.WorldPackage against the published description of what it writes.
//
// The schema of world.json (CarlaControl/schemas/world_package_manifest.schema.json) is generated by
// carlacontrol.WorldPackageSchemas, in Python, and the C# record is what writes the file. These tests
// hold the two together: the manifest WorldPackage.Write writes names exactly the fields the schema
// names, each of the JSON type the schema gives it; the fields the schema requires are the record's
// required members; and the record of what made the package has the schema's fields.
//
// The layout of bareearth.bin is described in words (Docs/CAT_Research/Schemas/Bare_Earth_Grid.md) and
// by carlacontrol.WorldPackageSchemas.BARE_EARTH_HEADER. The last test reads a written grid entry at
// the byte offsets that page gives.
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using System.IO;
using System.IO.Compression;
using System.Linq;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Text;
using System.Text.Json;
using CarlaNet.Map.WorldPackage;
using CarlaNet.Types.Provenance;

namespace CarlaNet.Tests.Map;

public class WorldPackageSchemaTests : IDisposable
{
    private readonly string _dir;

    public WorldPackageSchemaTests()
    {
        _dir = Path.Combine(Path.GetTempPath(), "carlanet-world-package-schema-" + Guid.NewGuid().ToString("N"));
        Directory.CreateDirectory(_dir);
    }

    public void Dispose()
    {
        try { Directory.Delete(_dir, recursive: true); } catch (IOException) { /* best effort */ }
        GC.SuppressFinalize(this);
    }

    private const int Columns = 5;
    private const int Rows = 3;

    private static WorldPackageManifest Manifest() => new()
    {
        Producer = Producer.Now(ServerBuildIdentity.NotAnswered("a server built before the call", "0.10.0", "1.0"),
                                "1.27.0"),
        MapName = "SchemaArea",
        OriginLatitude = 39.59431,
        OriginLongitude = -104.88449,
        OriginHeightMeters = 1747.40324,
        GeoReferenceString = "+proj=tmerc +lat_0=39.59431 +lon_0=-104.88449",
        HeightAlignMode = "drape",
        DrapeActive = true,
        HeightAlignOffsetMeters = 0.0,
        GridMinXMeters = -4.0,
        GridMinYMeters = -2.0,
        GridCellSizeMeters = 2.0,
        GridNumCols = Columns,
        GridNumRows = Rows,
        PhotorealIonAssetId = 2275207,
        GroundIonAssetId = 1,
        StagingMinXMeters = -4.0,
        StagingMinYMeters = -2.0,
        StagingMaxXMeters = 4.0,
        StagingMaxYMeters = 2.0,
        StagingMarginMeters = 30.48,
        SourceOsmFileName = "SchemaArea.osm",
        NetconvertArgv = ["--osm-files", "SchemaArea.osm"],
        NetconvertExtraArgs = ["--keep-edges.by-vclass", "passenger"],
    };

    private static (float[] Offset, float[] Ground) Grids()
    {
        var offset = new float[Columns * Rows];
        var ground = new float[Columns * Rows];
        for (int i = 0; i < offset.Length; i++)
        {
            offset[i] = -1.5f + i * 0.25f;
            ground[i] = 1715.0f + i;
        }
        return (offset, ground);
    }

    private string WritePackage()
    {
        var (offset, ground) = Grids();
        WorldPackage.Write(_dir, Manifest(), "<OpenDRIVE/>", "<net/>", offset, ground);
        return WorldPackage.PackagePath(_dir, "SchemaArea");
    }

    private static byte[] Entry(string package, string name)
    {
        using var archive = ZipFile.OpenRead(package);
        using var stream = archive.GetEntry(name)!.Open();
        using var buffer = new MemoryStream();
        stream.CopyTo(buffer);
        return buffer.ToArray();
    }

    private static JsonElement Schema()
    {
        string path = Path.Combine(CheckoutRoot(), "CarlaControl", "schemas", "world_package_manifest.schema.json");
        return JsonDocument.Parse(File.ReadAllText(path)).RootElement.Clone();
    }

    /// <summary>The JSON types a schema node allows, following its anyOf and a local $ref to an object.</summary>
    private static HashSet<string> Types(JsonElement node)
    {
        var types = new HashSet<string>();
        if (node.TryGetProperty("type", out JsonElement type))
        {
            types.Add(type.GetString()!);
        }
        if (node.TryGetProperty("const", out JsonElement constant))
        {
            types.Add(constant.ValueKind == JsonValueKind.Number ? "integer" : constant.ValueKind.ToString().ToLowerInvariant());
        }
        if (node.TryGetProperty("enum", out _))
        {
            types.Add("string");
        }
        if (node.TryGetProperty("$ref", out _))
        {
            types.Add("object");
        }
        if (node.TryGetProperty("anyOf", out JsonElement anyOf))
        {
            foreach (JsonElement branch in anyOf.EnumerateArray())
            {
                types.UnionWith(Types(branch));
            }
        }
        return types;
    }

    private static string Kind(JsonElement value) => value.ValueKind switch
    {
        JsonValueKind.String => "string",
        JsonValueKind.Number => value.TryGetInt64(out _) && !value.GetRawText().Contains('.') ? "integer" : "number",
        JsonValueKind.True or JsonValueKind.False => "boolean",
        JsonValueKind.Array => "array",
        JsonValueKind.Object => "object",
        _ => "null",
    };

    [Fact]
    public void TheManifestNamesExactlyTheFieldsTheSchemaNames()
    {
        JsonElement written = JsonDocument.Parse(Entry(WritePackage(), "world.json")).RootElement;
        JsonElement properties = Schema().GetProperty("properties");

        var writtenNames = written.EnumerateObject().Select(p => p.Name).ToHashSet();
        var schemaNames = properties.EnumerateObject().Select(p => p.Name).ToHashSet();
        Assert.Equal(schemaNames.OrderBy(n => n, StringComparer.Ordinal), writtenNames.OrderBy(n => n, StringComparer.Ordinal));
    }

    [Fact]
    public void EveryWrittenFieldIsOfTheTypeTheSchemaGivesIt()
    {
        JsonElement written = JsonDocument.Parse(Entry(WritePackage(), "world.json")).RootElement;
        JsonElement properties = Schema().GetProperty("properties");

        foreach (JsonProperty field in written.EnumerateObject())
        {
            HashSet<string> allowed = Types(properties.GetProperty(field.Name));
            string kind = Kind(field.Value);
            // A JSON integer is also a JSON number: a double whose value is whole is written without a point.
            bool fits = allowed.Contains(kind) || (kind == "integer" && allowed.Contains("number"));
            Assert.True(fits, $"{field.Name} is written as {kind}; the schema allows {string.Join(", ", allowed)}");
        }
    }

    [Fact]
    public void TheSchemaRequiresTheRecordsRequiredMembers()
    {
        var requiredMembers = typeof(WorldPackageManifest)
            .GetProperties(BindingFlags.Public | BindingFlags.Instance)
            .Where(p => p.GetCustomAttribute<RequiredMemberAttribute>() is not null)
            .Select(p => p.Name)
            .OrderBy(n => n, StringComparer.Ordinal);
        var required = Schema().GetProperty("required").EnumerateArray().Select(e => e.GetString()!)
            .OrderBy(n => n, StringComparer.Ordinal);
        Assert.Equal(requiredMembers, required);
    }

    [Fact]
    public void TheRecordOfWhatMadeThePackageHasTheSchemasFields()
    {
        JsonElement written = JsonDocument.Parse(Entry(WritePackage(), "world.json")).RootElement;
        // The manifest's Producer is the record, or null; the record's server is null, a server that
        // answered, or one that did not.
        JsonElement producer = Schema().GetProperty("properties").GetProperty("Producer").GetProperty("anyOf")[0];
        var allowed = producer.GetProperty("properties").EnumerateObject().Select(p => p.Name).ToHashSet();
        var required = producer.GetProperty("required").EnumerateArray().Select(e => e.GetString()!).ToHashSet();

        var names = written.GetProperty("Producer").EnumerateObject().Select(p => p.Name).ToHashSet();
        Assert.Subset(allowed, names);
        Assert.Superset(required, names);

        JsonElement unavailable = producer.GetProperty("properties").GetProperty("server").GetProperty("anyOf")
            .EnumerateArray()
            .Single(form => form.TryGetProperty("properties", out JsonElement members)
                            && members.TryGetProperty("reason", out _));
        var serverNames = written.GetProperty("Producer").GetProperty("server").EnumerateObject().Select(p => p.Name);
        Assert.Equal(unavailable.GetProperty("required").EnumerateArray().Select(e => e.GetString()!).OrderBy(n => n, StringComparer.Ordinal),
                     serverNames.OrderBy(n => n, StringComparer.Ordinal));
    }

    [Fact]
    public void TheGridEntryHasTheLayoutItsFormatPageGives()
    {
        byte[] grid = Entry(WritePackage(), "bareearth.bin");
        var (offset, ground) = Grids();

        // Byte offsets as Bare_Earth_Grid.md tabulates them; every value little-endian.
        Assert.Equal(60 + 2 * 4 * Columns * Rows, grid.Length);
        Assert.Equal("1PWC", Encoding.ASCII.GetString(grid, 0, 4));
        Assert.Equal(0x43575031, BinaryPrimitives.ReadInt32LittleEndian(grid.AsSpan(0)));
        Assert.Equal(39.59431, BinaryPrimitives.ReadDoubleLittleEndian(grid.AsSpan(4)));
        Assert.Equal(-104.88449, BinaryPrimitives.ReadDoubleLittleEndian(grid.AsSpan(12)));
        Assert.Equal(1747.40324, BinaryPrimitives.ReadDoubleLittleEndian(grid.AsSpan(20)));
        Assert.Equal(-4.0, BinaryPrimitives.ReadDoubleLittleEndian(grid.AsSpan(28)));
        Assert.Equal(-2.0, BinaryPrimitives.ReadDoubleLittleEndian(grid.AsSpan(36)));
        Assert.Equal(2.0, BinaryPrimitives.ReadDoubleLittleEndian(grid.AsSpan(44)));
        Assert.Equal(Columns, BinaryPrimitives.ReadInt32LittleEndian(grid.AsSpan(52)));
        Assert.Equal(Rows, BinaryPrimitives.ReadInt32LittleEndian(grid.AsSpan(56)));

        // The offset plane from byte 60, then the ground plane; row-major, index row * columns + column.
        int plane = 4 * Columns * Rows;
        for (int row = 0; row < Rows; row++)
        {
            for (int column = 0; column < Columns; column++)
            {
                int index = row * Columns + column;
                Assert.Equal(offset[index], BinaryPrimitives.ReadSingleLittleEndian(grid.AsSpan(60 + 4 * index)));
                Assert.Equal(ground[index], BinaryPrimitives.ReadSingleLittleEndian(grid.AsSpan(60 + plane + 4 * index)));
            }
        }
    }

    private static string CheckoutRoot()
    {
        for (DirectoryInfo? directory = new(AppContext.BaseDirectory); directory is not null; directory = directory.Parent)
        {
            string candidate = Path.Combine(directory.FullName, "CMakeLists.txt");
            if (File.Exists(candidate) && File.ReadAllText(candidate).Contains("CARLA_VERSION_MAJOR"))
            {
                return directory.FullName;
            }
        }

        throw new InvalidOperationException("the test is not running inside a CARLA checkout");
    }
}
