"""Write a multi-day SUMO route file: time-windowed ambient flows plus scheduled vehicles.

Where `SumoScenarioBuilder` writes one marked vehicle against steady background flows, a
pattern-of-life scenario is a timeline. Dozens of ambient flows switch on and off through each day
to give the map a diurnal rhythm and to fire ferry and shift-change pulses at set times; on top of
that sit individually scheduled vehicles -- guard-relief runs, an escort convoy, the planted
anomalies -- each departing at its own instant and following its own route, some pausing at
checkpoints or dwelling for hours.

The point of a week of this is an *established pattern of life*: enough repetition that the baseline
is learnable, so a deviation from it -- a relief run that skips a post, a convoy that appears where
the routine haul never does, a vehicle that loiters at a gate without entering -- is detectable
precisely because everything around it is regular.

Two SUMO rules shape the writer:

  * the route file must be sorted by departure time across flows and vehicles alike, so both are
    merged onto one timeline before writing (a single out-of-order entry is dropped with only a
    warning);
  * vehicle-type definitions must precede anything that references them, so the type block is
    written first, ahead of the timeline.
"""
from __future__ import annotations

import logging
from dataclasses import dataclass, field
from pathlib import Path

from carlacontrol.SumoScenarioBuilder import AmbientFlow, RoadNetwork

GENERATED_BY = "carlacontrol.SumoPatternOfLifeBuilder"


@dataclass(frozen=True)
class ScheduleStop:
    """A halt in a scheduled vehicle's run: a checkpoint pause, a relief drop, a long dwell.

    `duration` is seconds. `parking` takes the vehicle off the running lane (it keeps being
    reported, but stops obstructing the road) -- the right choice for a long dwell on a road that
    other traffic shares.
    """

    lane: str
    end_pos: float
    duration: float
    parking: bool = False


@dataclass(frozen=True)
class ScheduledVehicle:
    """One vehicle inserted at a set time on a routed trip, optionally flagged as an anomaly.

    SUMO routes the trip itself from `from_edge` to `to_edge`; `via` edges hold it to the intended
    path where the shortest route would differ. `marked` records that this vehicle is a planted
    anomaly, so the telemetry can label it as ground truth.
    """

    veh_id: str
    vehicle_type: str
    depart: float
    from_edge: str
    to_edge: str
    via: tuple[str, ...] = ()
    stops: tuple[ScheduleStop, ...] = ()
    color: str | None = None
    marked: bool = False
    depart_speed: str = "max"

    @property
    def sort_key(self) -> float:
        return self.depart


@dataclass
class PatternPaths:
    """What a build wrote, and the ground-truth anomaly index."""

    routes: Path
    config: Path
    end_time: int = 0
    flows: int = 0
    scheduled: int = 0
    marked_ids: list[str] = field(default_factory=list)


class SumoPatternOfLifeBuilder:
    """Writes the .rou.xml and .sumocfg for a multi-day pattern-of-life scenario."""

    def __init__(self, logger: logging.Logger | None = None):
        self.logger = logger or logging.getLogger(__name__)

    def write_routes(self, out_path: str | Path, network: RoadNetwork, vehicle_types_xml: str,
                     flows: list[AmbientFlow], scheduled: list[ScheduledVehicle],
                     end_time: int, title: str = "") -> list[str]:
        """Write the route file and return the ids of the vehicles flagged as anomalies."""
        out_path = Path(out_path)
        self._validate(network, flows, scheduled)

        # Merge flows and vehicles onto one timeline; SUMO drops anything out of departure order.
        timeline: list[tuple[float, str]] = []
        for flow in flows:
            timeline.append((flow.begin, self._flow_xml(flow, end_time)))
        for vehicle in sorted(scheduled, key=lambda v: v.sort_key):
            timeline.append((vehicle.depart, self._vehicle_xml(network, vehicle)))
        timeline.sort(key=lambda item: item[0])
        body = "\n".join(xml for _, xml in timeline)

        out_path.parent.mkdir(parents=True, exist_ok=True)
        # The header counts flows and vehicles but not how many of them were planted: this file
        # travels with the corpus, and the count is part of the answer. It is in the labels sidecar.
        out_path.write_text(f"""<?xml version="1.0" encoding="UTF-8"?>
<!-- {title or "Pattern-of-life scenario"}: {len(flows)} ambient flows over {end_time // 86400} day(s)
     plus {len(scheduled)} scheduled vehicles. Generated by {GENERATED_BY}; edit that, not this. -->
<routes xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="http://sumo.dlr.de/xsd/routes_file.xsd">

{vehicle_types_xml}
{body}

</routes>
""", encoding="utf-8")
        return [v.veh_id for v in scheduled if v.marked]

    # -- XML fragments -------------------------------------------------------------------------

    def _flow_xml(self, flow: AmbientFlow, end_time: int) -> str:
        via = f' via="{" ".join(flow.via)}"' if flow.via else ""
        end = end_time if flow.end is None else flow.end
        return (f'    <flow id="{flow.flow_id}" type="{flow.vehicle_type}" '
                f'begin="{flow.begin:.0f}" end="{end:.0f}"\n'
                f'          vehsPerHour="{flow.vehicles_per_hour}" '
                f'from="{flow.from_edge}" to="{flow.to_edge}"{via}\n'
                f'          departLane="free" departSpeed="max"/>')

    def _vehicle_xml(self, network: RoadNetwork, vehicle: ScheduledVehicle) -> str:
        via = f' via="{" ".join(vehicle.via)}"' if vehicle.via else ""
        colour = f' color="{vehicle.color}"' if vehicle.color else ""
        attrs = (f'    <trip id="{vehicle.veh_id}" type="{vehicle.vehicle_type}" '
                 f'depart="{vehicle.depart:.0f}"{colour}\n'
                 f'          from="{vehicle.from_edge}" to="{vehicle.to_edge}"{via}\n'
                 f'          departLane="best" departSpeed="{vehicle.depart_speed}" '
                 f'arrivalSpeed="current"')
        if not vehicle.stops:
            return attrs + "/>"
        stops = "\n".join(
            f'        <stop lane="{s.lane}" endPos="{s.end_pos:.2f}" duration="{s.duration:.0f}"'
            f' parking="{"true" if s.parking else "false"}"/>'
            for s in vehicle.stops)
        return attrs + ">\n" + stops + "\n    </trip>"

    def _validate(self, network: RoadNetwork, flows: list[AmbientFlow],
                  scheduled: list[ScheduledVehicle]) -> None:
        edges = network.edge_ids
        missing: set[str] = set()
        for flow in flows:
            for edge_id in (flow.from_edge, flow.to_edge, *flow.via):
                if edge_id not in edges:
                    missing.add(edge_id)
        for vehicle in scheduled:
            for edge_id in (vehicle.from_edge, vehicle.to_edge, *vehicle.via):
                if edge_id not in edges:
                    missing.add(edge_id)
            for stop in vehicle.stops:
                if stop.lane.rsplit("_", 1)[0] not in edges:
                    missing.add(stop.lane)
        if missing:
            raise ValueError("route references edges not in the network: "
                             + ", ".join(sorted(missing)[:12]))
