// Sources: carla/rpc/WheelPhysicsControl.h, VehiclePhysicsControl.h
namespace CarlaNet.Types.Rpc.Physics;

// Source: WheelPhysicsControl.h
// MSGPACK_DEFINE_ARRAY verified against source — 38 fields in declaration order
[MessagePackObject]
public record struct WheelPhysicsControl(
    [property: Key(0)]  byte AxleType,
    [property: Key(1)]  Vector3D Offset,
    [property: Key(2)]  float WheelRadius,
    [property: Key(3)]  float WheelWidth,
    [property: Key(4)]  float WheelMass,
    [property: Key(5)]  float CorneringStiffness,
    [property: Key(6)]  float FrictionForceMultiplier,
    [property: Key(7)]  float SideSlipModifier,
    [property: Key(8)]  float SlipThreshold,
    [property: Key(9)]  float SkidThreshold,
    [property: Key(10)] float MaxSteerAngle,
    [property: Key(11)] bool AffectedBySteering,
    [property: Key(12)] bool AffectedByBrake,
    [property: Key(13)] bool AffectedByHandbrake,
    [property: Key(14)] bool AffectedByEngine,
    [property: Key(15)] bool AbsEnabled,
    [property: Key(16)] bool TractionControlEnabled,
    [property: Key(17)] float MaxWheelspinRotation,
    [property: Key(18)] byte ExternalTorqueCombineMethod,
    [property: Key(19)] IReadOnlyList<Vector2D> LateralSlipGraph,
    [property: Key(20)] Vector3D SuspensionAxis,
    [property: Key(21)] Vector3D SuspensionForceOffset,
    [property: Key(22)] float SuspensionMaxRaise,
    [property: Key(23)] float SuspensionMaxDrop,
    [property: Key(24)] float SuspensionDampingRatio,
    [property: Key(25)] float WheelLoadRatio,
    [property: Key(26)] float SpringRate,
    [property: Key(27)] float SpringPreload,
    [property: Key(28)] int SuspensionSmoothing,
    [property: Key(29)] float RollbarScaling,
    [property: Key(30)] byte SweepShape,
    [property: Key(31)] byte SweepType,
    [property: Key(32)] float MaxBrakeTorque,
    [property: Key(33)] float MaxHandBrakeTorque,
    [property: Key(34)] int WheelIndex,
    [property: Key(35)] Location Location,
    [property: Key(36)] Location OldLocation,
    [property: Key(37)] Location Velocity);

// Source: VehiclePhysicsControl.h
// MSGPACK_DEFINE_ARRAY order verified from source — 30 fields
[MessagePackObject]
public record struct VehiclePhysicsControl(
    [property: Key(0)]  IReadOnlyList<Vector2D> TorqueCurve,
    [property: Key(1)]  float MaxTorque,
    [property: Key(2)]  float MaxRpm,
    [property: Key(3)]  float IdleRpm,
    [property: Key(4)]  float BrakeEffect,
    [property: Key(5)]  float RevUpMoi,
    [property: Key(6)]  float RevDownRate,
    [property: Key(7)]  byte DifferentialType,
    [property: Key(8)]  float FrontRearSplit,
    [property: Key(9)]  bool UseAutomaticGears,
    [property: Key(10)] float GearChangeTime,
    [property: Key(11)] float FinalRatio,
    [property: Key(12)] IReadOnlyList<float> ForwardGearRatios,
    [property: Key(13)] IReadOnlyList<float> ReverseGearRatios,
    [property: Key(14)] float ChangeUpRpm,
    [property: Key(15)] float ChangeDownRpm,
    [property: Key(16)] float TransmissionEfficiency,
    [property: Key(17)] float Mass,
    [property: Key(18)] float DragCoefficient,
    [property: Key(19)] Location CenterOfMass,
    [property: Key(20)] float ChassisWidth,
    [property: Key(21)] float ChassisHeight,
    [property: Key(22)] float DownforceCoefficient,
    [property: Key(23)] float DragArea,
    [property: Key(24)] Vector3D InertiaTensorScale,
    [property: Key(25)] float SleepThreshold,
    [property: Key(26)] float SleepSlopeLimit,
    [property: Key(27)] IReadOnlyList<Vector2D> SteeringCurve,
    [property: Key(28)] IReadOnlyList<WheelPhysicsControl> Wheels,
    [property: Key(29)] bool UseSweepWheelCollision);
