using System.Buffers.Binary;
using CarlaNet.Sumo;

namespace CarlaNet.Sumo.Tests;

/// <summary>
/// The outgoing half of the frame codec, checked byte for byte against what SUMO's own client
/// produces.
/// </summary>
/// <remarks>
/// <para>Every expected value here was generated by driving <c>tools/traci</c>'s own
/// <c>Connection._pack</c> and the framing in <c>Connection._sendCmd</c> at the pinned commit, not
/// derived by reading the protocol. That is the point: two implementations of a wire format agree
/// on a byte sequence by accident about as often as two decoders agree on a decode.</para>
///
/// <para>These need no SUMO installation, and they are the check that fails first and most clearly
/// when the framing is wrong. A frame that is malformed but plausible is otherwise diagnosed as
/// "SUMO closed the connection", several layers away from the mistake.</para>
/// </remarks>
public class TraCIWriterTests
{
    /// <summary>The seven variables a co-simulation bridge subscribes, in the order it sends them.</summary>
    private static readonly int[] VehicleState = TraCIVariables.VehicleState;

    [Fact]
    public void TheHandshakeIsABareCommand()
    {
        TraCIWriter writer = new();
        writer.BeginBareCommand(TraCIConstants.CMD_GETVERSION);
        Assert.Equal("000000060200", Hex(writer));
    }

    [Fact]
    public void TheStepCarriesItsTargetTimeAsARawDouble()
    {
        TraCIWriter writer = new();
        writer.BeginBareCommand(TraCIConstants.CMD_SIMSTEP);
        writer.WriteRawDouble(0.0);
        Assert.Equal("0000000E0A020000000000000000", Hex(writer));
    }

    [Fact]
    public void ClosingIsABareCommand()
    {
        TraCIWriter writer = new();
        writer.BeginBareCommand(TraCIConstants.CMD_CLOSE);
        Assert.Equal("00000006027F", Hex(writer));
    }

    [Fact]
    public void AGetNamesItsVariableAndAnEmptyObject()
    {
        TraCIWriter writer = new();
        writer.BeginCommand(TraCIConstants.CMD_GET_SIM_VARIABLE, TraCIConstants.VAR_TIME, string.Empty);
        Assert.Equal("0000000B07AB6600000000", Hex(writer));
    }

    [Fact]
    public void AGetNamesItsObject()
    {
        TraCIWriter writer = new();
        writer.BeginCommand(TraCIConstants.CMD_GET_VEHICLE_VARIABLE, TraCIConstants.VAR_SPEED, "first");
        Assert.Equal("000000100CA440000000056669727374", Hex(writer));
    }

    [Fact]
    public void ASubscriptionCarriesItsIntervalWhereAVariableWouldGo()
    {
        TraCIWriter writer = new();
        writer.BeginSubscription(TraCIConstants.CMD_SUBSCRIBE_VEHICLE_VARIABLE,
                                 TraCIConstants.INVALID_DOUBLE_VALUE,
                                 TraCIConstants.INVALID_DOUBLE_VALUE,
                                 "first");
        writer.WriteRawUnsignedByte((byte)VehicleState.Length);
        foreach (int variable in VehicleState)
        {
            writer.WriteRawUnsignedByte((byte)variable);
        }

        Assert.Equal(
            "0000002723D4C1D0000000000000C1D00000000000000000000566697273740742434050514F5B",
            Hex(writer));
    }

    [Fact]
    public void RemovingASubscriptionIsOneWithNoVariablesInIt()
    {
        TraCIWriter writer = new();
        writer.BeginSubscription(TraCIConstants.CMD_SUBSCRIBE_VEHICLE_VARIABLE,
                                 TraCIConstants.INVALID_DOUBLE_VALUE,
                                 TraCIConstants.INVALID_DOUBLE_VALUE,
                                 "first");
        writer.WriteRawUnsignedByte(0);

        Assert.Equal("000000201CD4C1D0000000000000C1D000000000000000000005666972737400", Hex(writer));
    }

    [Fact]
    public void ASetCarriesOneTypedValue()
    {
        TraCIWriter writer = new();
        writer.BeginCommand(TraCIConstants.CMD_SET_VEHICLE_VARIABLE, TraCIConstants.REMOVE, "first");
        writer.WriteByte(TraCIConstants.REMOVE_VAPORIZED);

        Assert.Equal("000000120EC4810000000566697273740803", Hex(writer));
    }

    /// <summary>
    /// A command whose length does not fit in a byte is written in TraCI's escaped form: a zero
    /// where the length would be, then the length as four bytes -- which count themselves, so the
    /// number written is four more than the short form would have carried.
    /// </summary>
    [Fact]
    public void ALongCommandEscapesToAFourByteLength()
    {
        TraCIWriter writer = new();
        writer.BeginCommand(TraCIConstants.CMD_SET_VEHICLE_VARIABLE, TraCIConstants.MOVE_TO_XY, "first");
        writer.WriteCompoundHeader(7);
        writer.WriteString(new string('e', 240));
        writer.WriteInt(0);
        writer.WriteDouble(12.5);
        writer.WriteDouble(-3.25);
        writer.WriteDouble(90.0);
        writer.WriteByte(1);
        writer.WriteDouble(100.0);

        string frame = Hex(writer);
        Assert.StartsWith("000001390000000135C4B4", frame, StringComparison.Ordinal);
        Assert.Equal(313 * 2, frame.Length);
    }

    /// <summary>
    /// One instance serves a whole connection, so a command has to leave nothing of the last one
    /// behind. The failure this guards against is a frame that grows by the previous command's
    /// payload, which the length prefix then describes correctly and SUMO rejects for a reason that
    /// names neither command.
    /// </summary>
    [Fact]
    public void AWriterIsReusableAcrossCommands()
    {
        TraCIWriter writer = new();
        writer.BeginCommand(TraCIConstants.CMD_SET_VEHICLE_VARIABLE, TraCIConstants.MOVE_TO_XY, "first");
        writer.WriteString(new string('e', 300));
        writer.Finish();

        writer.BeginBareCommand(TraCIConstants.CMD_GETVERSION);
        Assert.Equal("000000060200", Hex(writer));
    }

    /// <summary>
    /// The frame's own length prefix counts itself, which is what a reader on the other end relies
    /// on to know how much to take off the socket.
    /// </summary>
    [Fact]
    public void TheFrameLengthCountsItself()
    {
        TraCIWriter writer = new();
        writer.BeginCommand(TraCIConstants.CMD_GET_VEHICLE_VARIABLE, TraCIConstants.VAR_SPEED, "first");
        ReadOnlySpan<byte> frame = writer.Finish().Span;
        Assert.Equal(frame.Length, BinaryPrimitives.ReadInt32BigEndian(frame));
    }

    private static string Hex(TraCIWriter writer) => Convert.ToHexString(writer.Finish().Span);
}
